all:
	gcc -O3 -std=c99 Rkf45.c Matrix_Library.c RK_Library.c Policy_Distributor.c DeferredTemporaryLifeAnnuity.c TemporaryLifeAnnuityPremium.c DisabilityAnnuity.c TermInsurance.c PureEndowment.c

      
