all:
	gcc -O3 -std=c99 Rkf45.c Matrix_Library.c RK_Library.c Policy_Distributor.c Policies/DeferredTemporaryLifeAnnuity.c Policies/TemporaryLifeAnnuityPremium.c Policies/DisabilityAnnuity.c Policies/TermInsurance.c Policies/PureEndowment.c minunit.h UnitTests.c

      
